<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="bhagyak" failures="1" tests="3" name="Extent Reports Test" time="0.15" errors="0" timestamp="2024-12-28T16:25:20 IST">
  <testcase classname="testngTestcases.Test1" name="doLogin" time="0.036"/>
  <testcase classname="testngTestcases.Test1" name="doSkip" time="0.004">
    <skipped/>
  </testcase> <!-- doSkip -->
  <testcase classname="testngTestcases.Test1" name="doUserReg" time="0.008">
    <failure type="java.lang.AssertionError" message="Intentionally failing">
      <![CDATA[java.lang.AssertionError: Intentionally failing
at testngTestcases.Test1.doUserReg(Test1.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doUserReg -->
</testsuite> <!-- Extent Reports Test -->
